### ISSUE TITLE
General Questions - Multihost, Spark Version and Apache Zeppelin

### ISSUE THREAD

**Issue by prof-schacht** [big-data-europe/docker-hadoop-spark-workbench#15]
Hi

I have only some general questions. How to you handle the docker containers on multiple physical hosts? 

Is it possible to extend the example to SPARK Version 2.0 and add also Apache Zeppelin as Notebook Driver to this repo? 

BR

**Comment by earthquakesan** [comment]
Hi @prof-schacht, 

for multiple physical hosts see [overlay networking in docker](https://docs.docker.com/engine/userguide/networking/get-started-overlay/)

spark 2.0.0 with hive is available in [our repo](https://github.com/big-data-europe/docker-spark), essentially you just need to change version number. You can see example setup of hadoop, spark + hive used for sqlspark application [here](https://github.com/earthquakesan/docker-sparklify-deploy).

I have no experience with Apache Zeppelin. Would recommend to take a look into existing docker images and see if something can work with remote Spark/Hadoop installation via configuration options (or Hive).

To scale HDFS you need to spawn more datanode containers and connect it to namenode, in the same manner as it defined in the docker-compose.yml

**Comment by earthquakesan** [comment]
Hi @prof-schacht,

For running a container on a particular node read on general tools docker swarm provides in [this article](https://docs.docker.com/swarm/scheduler/filter/) and how to use compose to use them in [this article](https://docs.docker.com/compose/swarm/). For instance, if you want to run a container on a node with "frontend" label (one of the docker hosts should have docker daemon with this label -- you setup labels in /etc/default/docker on Ubuntu 14.04) you would do something like this:
```
version: "2"
services:
  bar:
    image: bar
    labels:
      - "constraint:node==frontend"
```

For setting up docker automatically, we use ansible for the pilots in BDE project. You can find deliverables of the project [on the official web site](https://www.big-data-europe.eu/results/). What you should look for is in [D5.1 on page 8 (see ansible)](https://www.big-data-europe.eu/wp-content/uploads/D5.1_Generic_Big_Data_Integrator_Instance_I.pdf). We use it just for deploying the docker, but you can extend the scripts for your particular use case. I recommend using ansible for this task in general.

Regarding hadoop configuration it works as follows. Every service refer to a hadoop.env file. For example, namenode (see env_file):
```
  namenode:
    image: bde2020/hadoop-namenode:1.0.0
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    networks:
      - hadoop
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "50070:50070"
      - "8020:8020"
```

Then in hadoop.env you have variables of which include filename + parameter + value:
```
CORE_CONF_fs_defaultFS=hdfs://namenode:8020
```
This variable will inject fs.defaultFS with value hdfs://namenode:8020 into core-site.xml. The injection of the vars are defined in [this script](https://github.com/big-data-europe/docker-hadoop/blob/master/base/entrypoint.sh), which is part of docker-hadoop repo.

Please, make a pull request, when you are done. That would be a really nice contribution to the project! If you need any help, do not hesitate to ask.
