### ISSUE TITLE
Unable to view worker details or Jobs

### ISSUE THREAD

**Issue by brett--anderson** [big-data-europe/docker-hadoop-spark-workbench#16]
I recently ran the docker stack on my dev machine (OSX 10.11.5 (15F34)) running Docker Native (Version 1.12.1 (build: 12133)).

I've tried some of the notebooks in the 'core' folder and these appear to work.

I'm now trying to run the Twitter Stream example which appears to be running a Spark Job, but I'm not seeing any output from the unordered list or geo widgets. In fact, they don't seem to be displaying at all.

I'm trying to diagnose the problem, but when I click the 'open SparkUI' button in the notebook, it tries to open http://192.168.0.10:4040/, this fails to load. I'm using Docker native so all my containers are addressable at local host. I also couldn't see the 4040 port being mapped in the docker-compose file. I tried adding it to the docker master and worker, but it still fails to load.

I've also found that I can load the Spark master web UI at  http://localhost:8080/. This works and I can see one worker. When I try and click on the worker it takes me to http://192.168.0.6:8081/ which fails to load. I've tried adding port 8081 to the docker compose file for both the master and worker, no dice.

So this issue is primarily about being unable to access the worker web UI and SparkUI via the notebook. If the widgets not appearing is a common issue, I'd like to know how to solve that too.

Thanks.

**Comment by brett--anderson** [comment]
The widgets not displaying seems to be a Notebook issue, as discussed here: https://github.com/andypetrella/spark-notebook/issues/730

But the primary issues around accessing the web interfaces still stands.

**Comment by earthquakesan** [comment]
Hi @brett--anderson!

Networking happens inside its own network which is 192.168.0.0/24 in your case (on linux the network is different). Components can talk to each other on the server side just fine. The problem is that this network is not exposed to your machine. 
You figured the work around: you will need to expose the ports directly. However, in the GUIs components will inject internal IP addresses into the links. Thus, when you are modifying docker-compose, you will have to open links in the browser directly.

For example:
```
  spark-worker:
    image: earthquakesan/hadoop-spark-worker:1.0.0
    hostname: spark-worker
    domainname: hadoop
    networks: 
      - hadoop
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - SPARK_CONF_spark_eventLog_enabled=true
      - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
      - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
      - SPARK_MASTER_URL=spark://spark-master:7077
    env_file:
      - ./hadoop.env
    ports:
      - "8081:8081"
```

Then you will be able to open spark-worker on localhost:8081, but can not access it from spark-master.
