### ISSUE TITLE
Question: how to connect from external client (intellij) to spark?

### ISSUE THREAD

**Issue by tomer-ben-david** [big-data-europe/docker-hadoop-spark-workbench#44]
Hi, I tried looking at `http://localhost:8080` and saw that sparkmaster is at: `spark://26a6a4b99956:7077` i'm not sure i was doing the correct thing but i tried creating spark conf (in local intellij) with: `val conf = new SparkConf().setAppName("myapp").setMaster("spark://26a6a4b99956:7077")`

but when tried to run some spark code i get:  

```
17/12/31 13:10:40 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://26a6a4b99956:7077...
17/12/31 13:10:40 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 26a6a4b99956:7077
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:205)
```

I tried playing with `network_mode: host` in the spark subsection but didnt work either.

is there a standard way that you know that I could start this cluster up and then connect to it with some spark code from my client (currently my intellij).

thanks

**Comment by earthquakesan** [comment]
Hi @tomer-ben-david!

in docker-compose.yml, you can find spark-master service:
```
spark-master:
    image: bde2020/spark-master:2.1.0-hadoop2.8-hive-java8
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
```
spark-master publishes ports 8080 and 7077 to localhost, thus you can connect to spark from intellij as: spark://localhost:7077
